### ISSUE TITLE
A feature to add all executables in a directory instead of just one exe at a time + option for checking the hash to virustotal.com

### ISSUE THREAD

**Issue by coopfidgets** [pylorak/TinyWall#46] opened 2024-07-17 16:26 UTC
thanks

**Comment by 9ao9ai9ar** [comment] 2024-07-30 17:14
Please close the issue yourself as it is a duplicate of https://github.com/pylorak/TinyWall/issues/4, https://github.com/pylorak/TinyWall/issues/35, https://github.com/pylorak/TinyWall/issues/40 and https://github.com/pylorak/TinyWall/issues/44, and upvote the OP on https://github.com/pylorak/TinyWall/issues/4 instead, where the author of TinyWall has also personally pitched in with the conversation.

As for the option to check the hash on VirusTotal, I believe this feature already exists:

![Screenshot 2024-07-31 011310](https://github.com/user-attachments/assets/9025070b-cfce-42bd-a9f5-3d0d37535319)

**Closed** 2024-07-31 20:43 UTC
