### ISSUE TITLE
Suggestion: Whitelist folder

### ISSUE THREAD

**Issue by AldebaraanMKII** [pylorak/TinyWall#40] opened 2024-05-08 01:25 UTC
Some programs (e.g. Discord, Github desktop) create a new folder every time a new update is auto installed (this can happen daily), which renders the current whitelist for that program useless. So my suggestion is to add the ability to whitelist a whole folder so any program who runs from that folder and subfolders get the rules applied to them.

**Comment by Shuggaloaf** [comment] 2024-05-21 23:26
I was just dealing with this problem myself with Discord (though I'm here for another reason). This seems like a great solution to me! Using Discord as an example users could whitelist the Discord parent folder and any future exes in `app-x.x.xxxx` would just work. 

Now if only we could stop it getting removed from the visible taskbar tray... ;)

**Comment by 9ao9ai9ar** [comment] 2024-07-30 17:05
Please close the issue yourself as it is a duplicate of #4, #35, #44 and #46, and upvote the OP on #4 instead.

**Comment by pylorak** [comment] 2024-07-31 20:57
Duplicate of #4.

**Closed by pylorak** 2024-07-31 20:57 UTC

**Comment by ChrisRosser** [comment] 2026-09-03 12:40
The Discord / GitHub Desktop case here is addressed by
https://github.com/pylorak/TinyWall/pull/133, though not by whitelisting a folder. When the
stored path disappears, the exception is followed into the sibling version folder and the path
rewritten, so a rule still points at exactly one executable rather than everything under a
directory.

If your goal was specifically folder-wide rules — anything that happens to run from that
directory — this doesn't do that, deliberately. Details and build caveats:
https://github.com/pylorak/TinyWall/issues/4#issuecomment-5525886082
