### ISSUE TITLE
Feature request: Masks for applications paths

### ISSUE THREAD

**Issue by agronatur** [pylorak/TinyWall#35] opened 2024-01-18 11:39 UTC
Some applications update on daily basis and like to change paths changing the folder name with their versions like:
C:\Program Files (x86)\Microsoft\EdgeWebView\Application\120.0.2210.133\msedgewebview2.exe
C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_1.226.1187.0_x64__zpdnekdrzrea0\Spotify.exe

so if we could do something like this:
C:\Program Files (x86)\Microsoft\EdgeWebView\Application\*\msedgewebview2.exe
C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_*\Spotify.exe

The * would allow anything.

**Comment by camheelio** [comment] 2024-01-19 10:52
I agree, using wildcards in the path would allow real "process-enablement". Currently even selecting a process creates a file rule limited to the exact and complete file path. And since more and more applications have it's version in the path (e.g. UltiMaker Cura, MSEdge, etc), it would allow to enable them without the need of modifying the rule after each update. Also it would cover UWP-Apps, that are not correctly placed in the group, like winget, which in theory should reside in the "DesktopAppInstaller"-UWP-Package but cannot be enabled by enabling this package. For this a simple 

*\winget.exe 

as file path could solve anything

**Comment by Rumpa112** [comment] 2024-05-29 20:14
Yeah, a much-needed future. As it stands now every time an app has a stupid version string in the path needs its firewall rule updated.

**Comment by 9ao9ai9ar** [comment] 2024-07-30 16:59
This issue is a duplicate of #4, where the author has pitched in with the conversation. I see the first step you could take is to download, if possible, a version of the program where the installation path doesn't change. For example, if you download directly from Spotify and not use the Microsoft Store version, you could avoid the hassle of needing to adjust the firewall rules on each update.

The second step you could take is to direct your complaints to the authors of the programs that violate the path preservation contract. This may accelerate the process of them fixing this issue [like JetBrains has done with their Toolbox App](https://blog.jetbrains.com/toolbox-app/2023/08/toolbox-app-2-0-overhauls-installations-and-updates/#windows).

**Comment by pylorak** [comment] 2024-07-31 21:35
Duplicate of #4.

**Closed by pylorak** 2024-07-31 21:35 UTC

**Comment by ChrisRosser** [comment] 2026-09-03 12:40
Both of the paths in this request are handled by
https://github.com/pylorak/TinyWall/pull/133 — I used them as test cases:

- `EdgeWebView\Application\144.0.3719.82\msedgewebview2.exe` — bare version folder
- `WindowsApps\SpotifyAB.SpotifyMusic_1.226.1187.0_x64__zpdnekdrzrea0\Spotify.exe` — MSIX, where
  the package name, architecture and publisher id must all match and only the version may differ

It is not the wildcard/mask syntax asked for here: rather than making a rule match many paths,
it repairs the exception after an update by following the executable into the new sibling folder.
So exact-path matching is preserved.

Background and the caveats on the unofficial build are in
https://github.com/pylorak/TinyWall/issues/4#issuecomment-5525886082. Awaiting @pylorak's review.
